[workspace]
resolver = "2"
members = ["backend", "importer"]


[workspace.dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "trace"] }
anyhow = "1.0.104"

# Server-rendered templates for the "simple pages"
askama = "0.12"
askama_axum = "0.4"

# SQLite access
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "macros"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
