# Generated by Django 4.2.21 on 2025-07-16 10:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('last_known_status', models.CharField(blank=True, choices=[('MT', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('G', 'Good'), ('P', 'Poor')], max_length=2, null=True)),
                ('is_proxy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('no_card_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SellerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ygo_cards.card')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ygo_cards.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_person', models.BooleanField(default=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_ygo_cards.sellersource')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='cards',
            field=models.ManyToManyField(through='my_ygo_cards.Unite', to='my_ygo_cards.card'),
        ),
        migrations.AddField(
            model_name='lot',
            name='seller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_ygo_cards.seller'),
        ),
        migrations.AddConstraint(
            model_name='unite',
            constraint=models.UniqueConstraint(fields=('lot', 'card'), name='lot_card_unite_unique'),
        ),
    ]
