# Generated by Django 4.2.21 on 2025-07-16 10:41

from django.db import migrations


def add_default_seller_sources(apps, schema_editor):
    SellerSource = apps.get_model('my_ygo_cards', 'SellerSource')
    initial_sources = [
        {"name": "Cardmarket", "url": "https://www.cardmarket.com/"},
        {"name": "Relation", "url": None},
    ]
    for src in initial_sources:
        SellerSource.objects.get_or_create(name=src["name"], defaults={"url": src["url"]})



class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_seller_sources),
    ]
