# Generated by Django 4.2.21 on 2025-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0002_add_default_seller_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='shipment_file',
            field=models.FileField(blank=True, null=True, upload_to='shipment_files/'),
        ),
    ]
