# Generated by Django 4.2.21 on 2025-07-16 10:41

from datetime import date
from django.db import migrations



def add_default_budget(apps, schema_editor):
    MonthlyBudget = apps.get_model('my_ygo_cards', 'MonthlyBudget')
    initial_sources = [
        {"month": date(year=2024, month=8, day=1), "amount": 25.00},
        {"month": date(year=2025, month=7, day=1), "amount": 33.00},
    ]
    for src in initial_sources:
        MonthlyBudget.objects.get_or_create(
            month=src["month"],
            defaults={"amount": src["amount"]}
        )



class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0004_monthlybudget'),
    ]

    operations = [
        migrations.RunPython(add_default_budget),
    ]
