# Generated by Django 4.2.21 on 2025-08-26 06:18

from django.db import migrations, models

def add_default_card_en_name(apps, schema_editor):
    CardSource = apps.get_model('my_ygo_cards', 'Card')
    for card in CardSource.objects.all():
        card.en_name = card.name
        card.save()




class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0005_add_default_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(add_default_card_en_name),
    ]
