# Generated by Django 4.2.21 on 2025-08-26 06:18

from django.db import migrations, models

import re

def extract_code_information(code: str) -> tuple[str, str] | None:
    match = re.match(r"#(\d+)\s+([A-Za-z0-9]{4})", code)
    if match:
        return match.group(1), match.group(2)
    return None


def normalise_code(apps, schema_editor):
    CardSource = apps.get_model('my_ygo_cards', 'Card')
    for card in CardSource.objects.all():
        if card.code:
            info = extract_code_information(card.code)
            if info:
                new_code = f"{info[1]}-EN{info[0]}"
                if card.code != new_code:
                    card.code = new_code
                    card.save()




class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0006_card_en_name'),
    ]

    operations = [
        migrations.RunPython(normalise_code),
    ]
