# Generated by Django 4.2.21 on 2025-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0007_normalise_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(blank=True, related_name='decks', to='my_ygo_cards.card')),
            ],
        ),
    ]
