# Generated by Django 4.2.21 on 2025-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0008_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AddField(
            model_name='deck',
            name='extra_deck',
            field=models.ManyToManyField(blank=True, related_name='extra_decks', to='my_ygo_cards.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='main_deck',
            field=models.ManyToManyField(blank=True, related_name='main_decks', to='my_ygo_cards.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='side_deck',
            field=models.ManyToManyField(blank=True, related_name='side_decks', to='my_ygo_cards.card'),
        ),
    ]
