# Generated by Django 4.2.21 on 2025-09-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0009_remove_deck_cards_deck_extra_deck_deck_main_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('en_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ygopro_id', models.IntegerField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='my_ygo_cards.carddata'),
        ),
    ]
