# Generated by Django 4.2.21 on 2025-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0010_carddata_card_card_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_data',
        ),
        migrations.AddField(
            model_name='carddata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddata',
            name='en_name',
            field=models.CharField(max_length=255),
        ),
    ]
