# Generated by Django 4.2.21 on 2025-09-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0011_remove_card_card_data_carddata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='my_ygo_cards.carddata'),
        ),
    ]
