# Generated by Django 4.2.21 on 2025-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0012_card_card_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('name', 'source')},
        ),
    ]
