# Generated by Django 4.2.21 on 2025-09-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0013_alter_seller_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apports', to='my_ygo_cards.monthlybudget')),
            ],
        ),
    ]
