# Generated by Django 4.2.21 on 2025-09-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0015_tournament_rename_deck_deckversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckversion',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_ygo_cards.tournament'),
        ),
    ]
