# Generated by Django 4.2.21 on 2025-09-11 12:12

from django.db import migrations, models
from django.db.models import Count

def remove_duplicates(apps, schema_editor):
    CardData = apps.get_model('my_ygo_cards', 'CardData')

    # Find duplicate ygopro_ids
    duplicates = (
        CardData.objects
        .values('ygopro_id')
        .annotate(count_id=Count('id'))
        .filter(count_id__gt=1)
    )

    for entry in duplicates:
        ygopro_id = entry['ygopro_id']
        # Get all objects with this ygopro_id, ordered by id
        cards = CardData.objects.filter(ygopro_id=ygopro_id).order_by('id')
        first_card = cards.first()
        # Keep first, delete the rest
        cards_to_delete = cards[1:]
        for card in cards_to_delete:
            print(f"Deleting duplicate CardData with id {card.id} and ygopro_id {ygopro_id} (name: {card.en_name} vs {first_card.en_name})")
            card.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0016_deckversion_tournament'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterField(
            model_name='carddata',
            name='ygopro_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
