# Generated by Django 4.2.21 on 2025-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0018_deck_rename_name_deckversion_version_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lot_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], default='purchase', max_length=10),
        ),
    ]
