# Generated by Django 4.2.21 on 2025-11-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0019_lot_lot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deck_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='my_ygo_cards.deckversion')),
            ],
        ),
        migrations.CreateModel(
            name='CardCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ygo_cards.card')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ygo_cards.cardcategory')),
            ],
            options={
                'unique_together': {('category', 'card')},
            },
        ),
    ]
