# Generated by Django 4.2.21 on 2025-11-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0020_cardcategory_cardcategoryassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardConditionalCategory',
            fields=[
                ('cardcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_ygo_cards.cardcategory')),
                ('condition_description', models.TextField()),
                ('categorie_false', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_false', to='my_ygo_cards.cardcategory')),
                ('categorie_true', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_true', to='my_ygo_cards.cardcategory')),
                ('categories_or_conditions', models.ManyToManyField(blank=True, related_name='conditional_categories_or_conditions', to='my_ygo_cards.cardcategory')),
            ],
            bases=('my_ygo_cards.cardcategory',),
        ),
    ]
