# Generated by Django 4.2.21 on 2025-11-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0021_cardconditionalcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedBanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date when this ban list became effective', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BanListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Banned', 'Banned'), ('Limited', 'Limited'), ('Semi-Limited', 'Semi-Limited')], max_length=15)),
                ('ban_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='my_ygo_cards.advancedbanlist')),
                ('card_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ban_list_entries', to='my_ygo_cards.carddata')),
            ],
        ),
    ]
