# Generated by Django 4.2.21 on 2025-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0022_advancedbanlist_banlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='en_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
