# Generated by Django 4.2.21 on 2025-11-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0023_alter_carddata_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckversion',
            name='ban_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_ygo_cards.advancedbanlist'),
        ),
    ]
