# Generated by Django 4.2.21 on 2025-12-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ygo_cards', '0024_deckversion_ban_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The year of the Advent Calendar', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='The day of the month (1-25)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advent_calendar_photos/')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='my_ygo_cards.adventcalendar')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advent_calendar_entries', to='my_ygo_cards.card')),
            ],
            options={
                'unique_together': {('calendar', 'day')},
            },
        ),
    ]
